<img align="left" src="https://lever-client-logos.s3.amazonaws.com/864372b1-534c-480e-acd5-9711f850815c-1524247202159.png" width=200>
<br></br>
<br></br>

# Neural Networks

## *Data Science Unit 4 Sprint 2 Assignment 1*

## Define the Following:
You can add image, diagrams, whatever you need to ensure that you understand the concepts below.

### Input Layer: The part of a neural network that we want to analyze
### Hidden Layer: Part of the neural network that does the analysis of the input layer
### Output Layer: Tells us the results of the analysis provided by the hidden layer
### Neuron: They recieve inputs and pass results to the next layer
### Weight: A transformation value between layers of of a neural network
### Activation Function: Part of every node that determines how much information passes to the next NN layer. If the nodes are in the same layer, they usually have the same activation/transder function.
### Node Map: It is a flowchart of the neural network's layers.
### Perceptron: A neural network that has no hidden layers.


## Inputs -> Outputs

### Explain the flow of information through a neural network from inputs to outputs. Be sure to include: inputs, weights, bias, and activation functions. How does it all flow from beginning to end?

#### Your Answer Here

## Write your own perceptron code that can correctly classify (99.0% accuracy) a NAND gate. 

| x1 | x2 | y |
|----|----|---|
| 0  | 0  | 1 |
| 1  | 0  | 1 |
| 0  | 1  | 1 |
| 1  | 1  | 0 |

In [1]:
import pandas as pd
data = { 'x1': [0,1,0,1],
         'x2': [0,0,1,1],
         'y':  [1,1,1,0]
       }

df = pd.DataFrame.from_dict(data).astype('int')

In [2]:
inputs = df.iloc[:,:3].values
inputs



array([[0, 0, 1],
       [1, 0, 1],
       [0, 1, 1],
       [1, 1, 0]])

In [3]:
correct_outputs = df.iloc[:,2:].values
correct_outputs

array([[1],
       [1],
       [1],
       [0]])

In [4]:
import numpy as np

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    sx = sigmoid(x)
    return sx * (1-sx)

In [5]:
weights = 2 * np.random.random((3,1)) - 1
for _ in range(10000):
    weighted_sum = np.dot(inputs, weights)
    activated_output = sigmoid(weighted_sum)
    error = correct_outputs - activated_output
    adjustments = error * sigmoid_derivative(activated_output)
    weights += np.dot(inputs.T, adjustments)

print(f"Final weights are \n{weights}")
print(f"Final predictions are\n {activated_output}")

Final weights are 
[[-3.80700743]
 [-3.80661073]
 [11.69654718]]
Final predictions are
 [[9.99991676e-01]
 [9.99625461e-01]
 [9.99625610e-01]
 [4.93487856e-04]]


## Implement your own Perceptron Class and use it to classify a binary dataset: 
- [The Pima Indians Diabetes dataset](https://raw.githubusercontent.com/ryanleeallred/datasets/master/diabetes.csv) 

You may need to search for other's implementations in order to get inspiration for your own. There are *lots* of perceptron implementations on the internet with varying levels of sophistication and complexity. Whatever your approach, make sure you understand **every** line of your implementation and what its purpose is.

In [6]:
diabetes = pd.read_csv('https://raw.githubusercontent.com/ryanleeallred/datasets/master/diabetes.csv')
diabetes.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

Although neural networks can handle non-normalized data, scaling or normalizing your data will improve your neural network's learning speed. Try to apply the sklearn `MinMaxScaler` or `Normalizer` to your diabetes dataset. 

In [7]:
from sklearn.preprocessing import MinMaxScaler, Normalizer

feats = list(diabetes)[:-1]

X=diabetes.iloc[:,0:8].values
y=diabetes.iloc[:,-1].values

In [8]:
scaler = MinMaxScaler()
print(scaler.fit(diabetes))

MinMaxScaler(copy=True, feature_range=(0, 1))


C:\Users\daani\AppData\Local\Programs\Python\Python37\lib\site-packages\sklearn\preprocessing\data.py:323: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by MinMaxScaler.
  return self.partial_fit(X, y)


In [9]:
scaler.fit(X)
scale_X = scaler.transform(X)

In [10]:
scale_X.shape

(768, 8)

In [11]:
scale_X


array([[0.35294118, 0.74371859, 0.59016393, ..., 0.50074516, 0.23441503,
        0.48333333],
       [0.05882353, 0.42713568, 0.54098361, ..., 0.39642325, 0.11656704,
        0.16666667],
       [0.47058824, 0.91959799, 0.52459016, ..., 0.34724292, 0.25362938,
        0.18333333],
       ...,
       [0.29411765, 0.6080402 , 0.59016393, ..., 0.390462  , 0.07130658,
        0.15      ],
       [0.05882353, 0.63316583, 0.49180328, ..., 0.4485842 , 0.11571307,
        0.43333333],
       [0.05882353, 0.46733668, 0.57377049, ..., 0.45305514, 0.10119556,
        0.03333333]])

In [15]:
##### Update this Class #####

class Perceptron(object):
    
    def __init__(self, niter = 10):
        self.niter = niter
    
    def __sigmoid(self, x):
        return 1 / (1 + np.exp(-x))
        
    
    def __sigmoid_derivative(self, x):
        sx = sigmoid(x)
        return sx * (1-sx)
        

    def fit(self, X, y):
        """Fit training data
        X : Training vectors, X.shape : [#samples, #features]
        y : Target values, y.shape : [#samples]
        """

        # Randomly Initialize Weights
        self.weights = np.zeros(X.shape[1])

        for _ in range(self.niter):
            # Weighted sum of inputs / weights
            self.weighted_sum = np.dot(X, self.weights)
            # Activate!
            self.activated_output = self.__sigmoid(self.weighted_sum)
            # Calc error
            self.error = y - self.activated_output
            # Update the Weights
            self.adjustments = self.error * self.__sigmoid_derivative(self.activated_output)
            self.weights += np.dot(X.T, self.adjustments)
            
    def predict(self, X):
        """Return class label after unit step"""
#       return np.where((np.dot(X, self.weights[1:]) + self.weights[0])>= 0.0, 1, -1)
        return np.where((np.dot(X, self.weights))>= 0.0, 1, 0)

In [16]:
from sklearn.metrics import accuracy_score
dia_per = Perceptron(10000)
dia_per.fit(scale_X,y)
predictions = dia_per.predict(scale_X)
accuracy_score(y,predictions)


0.5052083333333334

## Stretch Goals:

- Research "backpropagation" to learn how weights get updated in neural networks (tomorrow's lecture). 
- Implement a multi-layer perceptron. (for non-linearly separable classes)
- Try and implement your own backpropagation algorithm.
- What are the pros and cons of the different activation functions? How should you decide between them for the different layers of a neural network?