<img align="left" src="https://lever-client-logos.s3.amazonaws.com/864372b1-534c-480e-acd5-9711f850815c-1524247202159.png" width=200>
<br></br>
<br></br>

## *Data Science Unit 4 Sprint 2*

# Sprint Challenge - Neural Network Foundations

Table of Problems

1. [Defining Neural Networks](#Q1)
2. [Chocolate Gummy Bears](#Q2)
    - Perceptron
    - Multilayer Perceptron
4. [Keras MMP](#Q3)

<a id="Q1"></a>
## 1. Define the following terms:

- **Neuron:**
- **Input Layer:**
- **Hidden Layer:**
- **Output Layer:**
- **Activation:**
- **Backpropagation:**


## 2. Chocolate Gummy Bears <a id="Q2"></a>

Right now, you're probably thinking, "yuck, who the hell would eat that?". Great question. Your candy company wants to know too. And you thought I was kidding about the [Chocolate Gummy Bears](https://nuts.com/chocolatessweets/gummies/gummy-bears/milk-gummy-bears.html?utm_source=google&utm_medium=cpc&adpos=1o1&gclid=Cj0KCQjwrfvsBRD7ARIsAKuDvMOZrysDku3jGuWaDqf9TrV3x5JLXt1eqnVhN0KM6fMcbA1nod3h8AwaAvWwEALw_wcB). 

Let's assume that a candy company has gone out and collected information on the types of Halloween candy kids ate. Our candy company wants to predict the eating behavior of witches, warlocks, and ghosts -- aka costumed kids. They shared a sample dataset with us. Each row represents a piece of candy that a costumed child was presented with during "trick" or "treat". We know if the candy was `chocolate` (or not chocolate) or `gummy` (or not gummy). Your goal is to predict if the costumed kid `ate` the piece of candy. 

If both chocolate and gummy equal one, you've got a chocolate gummy bear on your hands!?!?!
![Chocolate Gummy Bear](https://ed910ae2d60f0d25bcb8-80550f96b5feb12604f4f720bfefb46d.ssl.cf1.rackcdn.com/3fb630c04435b7b5-2leZuM7_-zoom.jpg)

In [1]:
import pandas as pd
candy = pd.read_csv('chocolate_gummy_bears.csv')

In [2]:
candy.head()

chocolate  gummy  ate
0          0      1    1
1          1      0    1
2          0      1    1
3          0      0    0
4          1      1    0

### Perceptron

To make predictions on the `candy` dataframe. Build and train a Perceptron using numpy. Your target column is `ate` and your features: `chocolate` and `gummy`. Do not do any feature engineering. :P

Once you've trained your model, report your accuracy. You will not be able to achieve more than ~50% with the simple perceptron. Explain why you could not achieve a higher accuracy with the *simple perceptron* architecture, because it's possible to achieve ~95% accuracy on this dataset. Provide your answer in markdown (and *optional* data anlysis code) after your perceptron implementation. 

In [3]:
# Start your candy perceptron here

X = candy[['chocolate', 'gummy']].values
y = candy['ate'].values

In [4]:
import numpy as np

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    sx = sigmoid(x)
    return sx * (1-sx)

In [5]:
weights = 2 * np.random.random((2,1)) - 1
weights

array([[ 0.25842608],
       [-0.72506561]])

In [6]:
weighted_sum = np.dot(X, weights)
weighted_sum

array([[-0.72506561],
       [ 0.25842608],
       [-0.72506561],
       ...,
       [-0.72506561],
       [-0.72506561],
       [ 0.25842608]])

In [7]:
y = np.reshape(y, (-1,1))


In [8]:
for iteration in range(10000):
    
    # Weighted sum of inputs / weights
    weighted_sum = np.dot(X, weights)
    
    # Activate!
    activated_output = sigmoid(weighted_sum)
    
    # Calc error
    error = y - activated_output
    
    adjustments = error * sigmoid_derivative(activated_output)
    
    # Update the Weights
    weights += np.dot(X.T, adjustments)

C:\Users\daani\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:4: RuntimeWarning: overflow encountered in exp
  after removing the cwd from sys.path.


In [9]:
activated_output = np.where(activated_output >= .5, 1, 0)


In [10]:
print(f"Final weights are \n{weights}")
print(f"Final predictions are\n {activated_output}")

Final weights are 
[[-213.18097755]
 [-190.80011325]]
Final predictions are
 [[1]
 [1]
 [1]
 ...
 [1]
 [1]
 [1]]


In [11]:
from sklearn.metrics import accuracy_score
print(f'Accuracy is {accuracy_score(y, activated_output.astype(int))}')

Accuracy is 0.5


### Multilayer Perceptron <a id="Q3"></a>

Using the sample candy dataset, implement a Neural Network Multilayer Perceptron class that uses backpropagation to update the network's weights. Your Multilayer Perceptron should be implemented in Numpy. 
Your network must have one hidden layer.

Once you've trained your model, report your accuracy. Explain why your MLP's performance is considerably better than your simple perceptron's on the candy dataset. 

In [12]:
class NeuralNetwork(object):
    
    def __init__(self):
        # Set up Architecture of Neural Network
        self.inputs = 2
        self.hiddenNodes =  64
        self.outputNodes = 1

        # Initial Weights
        self.weights1 = np.random.randn(self.inputs, self.hiddenNodes)
       
        # Weights for Hidden to Output
        self.weights2 = np.random.randn(self.hiddenNodes, self.outputNodes)
        
    def sigmoid(self, s):
        """Activation function to push to 1 or 0.
        """
        return 1 / (1+np.exp(-s))
    
    def sigmoidPrime(self, s):
        """Derivative of above.
        """
        return s * (1-s)
    
    def feed_forward(self, X):
        """
        Calculate the NN inference using feed forward pass.
        """
        # Weighted sum of inputs and hidden layer
        self.hidden_sum = np.dot(X, self.weights1)
        
        # Activation of the weighted sum
        self.activated_hidden = self.sigmoid(self.hidden_sum)
        
        # Weighted sum of hidden layer to output layer
        self.output_sum = np.dot(self.activated_hidden, self.weights2)
        
        # Final Activation of Output
        self.activated_output = self.sigmoid(self.output_sum)
        
        return self.activated_output
    
    def backward(self, X, y, o):
        """Send the error back and adjust the weights.
        """
        self.o_error = y - o #error in output
        
        #Size of Adjustment from hidden => output
        self.o_delta = self.o_error * self.sigmoidPrime(o) # apply derivate of sigmoid to error
        
        # z2 error: how much our input => hidden weights weights were off
        self.z2_error = self.o_delta.dot(self.weights2.T)
        self.z2_delta = self.z2_error * self.sigmoidPrime(self.activated_hidden)
        
        #Adjustment hidden => output weights
        self.weights2 += self.activated_hidden.T.dot(self.o_delta)
        
        #Adjustment input => hidden weights
        self.weights1 += X.T.dot(self.z2_delta)
        
    def train(self, X, y):
        """Train the net forward and back.
        """
        o = self.feed_forward(X) #o is output layer
        self.backward(X, y, o)

In [13]:
nn = NeuralNetwork()

In [14]:
np.unique(y), np.unique(X)

(array([0, 1], dtype=int64), array([0, 1], dtype=int64))

In [15]:
print("Predicted Output: \n" + str(nn.feed_forward(X))) 
print("Loss: \n" + str(np.mean(np.square(y - nn.feed_forward(X)))))

Predicted Output: 
[[0.84825554]
 [0.74073138]
 [0.84825554]
 ...
 [0.84825554]
 [0.84825554]
 [0.74073138]]
Loss: 
0.28212750208221266


In [16]:
print(f'Accuracy is {accuracy_score(y,np.round(nn.feed_forward(X)))}')

Accuracy is 0.7236


In [20]:
for i in range(10000):
    if(i+1 in [1,2,3,4,5]) or ((i+1)%1000 == 0):
        print('+'+'---'*3 +f'EPOCH {i+1}'+'---'*3 + '+')
        print('Input: \n', X)
        print('Actual Output: \n', y)
        print("Predicted Output: \n", str(nn.feed_forward(X)))
        print("Loss: \n", str(np.mean(np.square(y-nn.feed_forward(X)))))
    nn.train(X,y)

+---------EPOCH 1---------+
Input: 
 [[0 1]
 [1 0]
 [0 1]
 ...
 [0 1]
 [0 1]
 [1 0]]
Actual Output: 
 [[1]
 [1]
 [1]
 ...
 [1]
 [1]
 [1]]
Predicted Output: 
 [[0.84825554]
 [0.74073138]
 [0.84825554]
 ...
 [0.84825554]
 [0.84825554]
 [0.74073138]]
Loss: 
 0.28212750208221266
+---------EPOCH 2---------+
Input: 
 [[0 1]
 [1 0]
 [0 1]
 ...
 [0 1]
 [0 1]
 [1 0]]
Actual Output: 
 [[1]
 [1]
 [1]
 ...
 [1]
 [1]
 [1]]
Predicted Output: 
 [[0.]
 [0.]
 [0.]
 ...
 [0.]
 [0.]
 [0.]]
Loss: 
 0.5
+---------EPOCH 3---------+
Input: 
 [[0 1]
 [1 0]
 [0 1]
 ...
 [0 1]
 [0 1]
 [1 0]]
Actual Output: 
 [[1]
 [1]
 [1]
 ...
 [1]
 [1]
 [1]]
Predicted Output: 
 [[0.]
 [0.]
 [0.]
 ...
 [0.]
 [0.]
 [0.]]


C:\Users\daani\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:18: RuntimeWarning: overflow encountered in exp


Loss: 
 0.5
+---------EPOCH 4---------+
Input: 
 [[0 1]
 [1 0]
 [0 1]
 ...
 [0 1]
 [0 1]
 [1 0]]
Actual Output: 
 [[1]
 [1]
 [1]
 ...
 [1]
 [1]
 [1]]
Predicted Output: 
 [[0.]
 [0.]
 [0.]
 ...
 [0.]
 [0.]
 [0.]]
Loss: 
 0.5
+---------EPOCH 5---------+
Input: 
 [[0 1]
 [1 0]
 [0 1]
 ...
 [0 1]
 [0 1]
 [1 0]]
Actual Output: 
 [[1]
 [1]
 [1]
 ...
 [1]
 [1]
 [1]]
Predicted Output: 
 [[0.]
 [0.]
 [0.]
 ...
 [0.]
 [0.]
 [0.]]
Loss: 
 0.5
+---------EPOCH 1000---------+
Input: 
 [[0 1]
 [1 0]
 [0 1]
 ...
 [0 1]
 [0 1]
 [1 0]]
Actual Output: 
 [[1]
 [1]
 [1]
 ...
 [1]
 [1]
 [1]]
Predicted Output: 
 [[0.]
 [0.]
 [0.]
 ...
 [0.]
 [0.]
 [0.]]
Loss: 
 0.5
+---------EPOCH 2000---------+
Input: 
 [[0 1]
 [1 0]
 [0 1]
 ...
 [0 1]
 [0 1]
 [1 0]]
Actual Output: 
 [[1]
 [1]
 [1]
 ...
 [1]
 [1]
 [1]]
Predicted Output: 
 [[0.]
 [0.]
 [0.]
 ...
 [0.]
 [0.]
 [0.]]
Loss: 
 0.5
+---------EPOCH 3000---------+
Input: 
 [[0 1]
 [1 0]
 [0 1]
 ...
 [0 1]
 [0 1]
 [1 0]]
Actual Output: 
 [[1]
 [1]
 [1]
 ...
 [1]
 [1]

P.S. Don't try candy gummy bears. They're disgusting. 

## 3. Keras MMP <a id="Q3"></a>

Implement a Multilayer Perceptron architecture of your choosing using the Keras library. Train your model and report its baseline accuracy. Then hyperparameter tune at least two parameters and report your model's accuracy.
Use the Heart Disease Dataset (binary classification)
Use an appropriate loss function for a binary classification task
Use an appropriate activation function on the final layer of your network.
Train your model using verbose output for ease of grading.
Use GridSearchCV or RandomSearchCV to hyperparameter tune your model. (for at least two hyperparameters)
When hyperparameter tuning, show you work by adding code cells for each new experiment.
Report the accuracy for each combination of hyperparameters as you test them so that we can easily see which resulted in the highest accuracy.
You must hyperparameter tune at least 3 parameters in order to get a 3 on this section.

In [21]:
import pandas as pd
from sklearn.preprocessing import StandardScaler

df = pd.read_csv('https://raw.githubusercontent.com/ryanleeallred/datasets/master/heart.csv')
df = df.sample(frac=1)
print(df.shape)
df.head()

(303, 14)


age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
146   44    0   2       118   242    0        1      149      0      0.3   
178   43    1   0       120   177    0        0      120      1      2.5   
85    67    0   2       115   564    0        0      160      0      1.6   
153   66    0   2       146   278    0        0      152      0      0.0   
247   66    1   1       160   246    0        1      120      1      0.0   

     slope  ca  thal  target  
146      1   1     2       1  
178      1   0     3       0  
85       1   0     3       1  
153      1   1     2       1  
247      1   3     1       0

In [22]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.model_selection import GridSearchCV
from tensorflow.keras.wrappers.scikit_learn import KerasClassifier

In [23]:
scaler = StandardScaler()

X = scaler.fit_transform(df.iloc[:,:13])
y = df.target.values.reshape(-1,1)
     
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

C:\Users\daani\AppData\Local\Programs\Python\Python37\lib\site-packages\sklearn\preprocessing\data.py:625: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
  return self.partial_fit(X, y)
C:\Users\daani\AppData\Local\Programs\Python\Python37\lib\site-packages\sklearn\base.py:462: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
  return self.fit(X, **fit_params).transform(X)


In [24]:
print(X_train.shape, X_test.shape, y_test.shape, y_train.shape)


(242, 13) (61, 13) (61, 1) (242, 1)


In [25]:
model = Sequential()
model.add(Dense(20, input_dim=13, activation='relu'))
model.add(Dense(20, activation='relu'))
model.add(Dense(1, activation='sigmoid'))
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['mae','accuracy'])

In [26]:
model.summary()


Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 20)                280       
_________________________________________________________________
dense_1 (Dense)              (None, 20)                420       
_________________________________________________________________
dense_2 (Dense)              (None, 1)                 21        
Total params: 721
Trainable params: 721
Non-trainable params: 0
_________________________________________________________________


In [27]:
fit = model.fit(X_train, y_train, epochs=150, verbose=False)

scores = model.evaluate(X_train, y_train, verbose=False)
print("Train Loss, MAE, Accuracy", scores)
scores = model.evaluate(X_test, y_test, verbose=False)
print("Test Loss, MAE, Accuracy ", scores)

Train Loss, MAE, Accuracy [0.11214879915610818, 0.08154688, 0.96694213]
Test Loss, MAE, Accuracy  [0.5237035174838832, 0.18037309, 0.852459]


In [28]:
seed = 7
np.random.seed(seed)

# Function to create model, required for KerasClassifier
def create_model():
    # create model
    model = Sequential()
    model.add(Dense(12, input_dim=13, activation='relu'))
    model.add(Dense(1, activation='sigmoid'))
    # Compile model
    model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
    return model

# create model
model = KerasClassifier(build_fn=create_model, verbose=0)

# define the grid search parameters
# batch_size = [10, 20, 40, 60, 80, 100]
# param_grid = dict(batch_size=batch_size, epochs=epochs)

# define the grid search parameters
param_grid = {'batch_size': [10, 20, 40, 60, 80, 100],
              'epochs': [20]}

# Create Grid Search
grid = GridSearchCV(estimator=model, param_grid=param_grid, n_jobs=1)
grid_result = grid.fit(X_train, y_train, verbose=True)

# Report Results
means = grid_result.cv_results_['mean_test_score']
stds = grid_result.cv_results_['std_test_score']
params = grid_result.cv_results_['params']
for mean, stdev, param in zip(means, stds, params):
    print(f"Means: {mean}, Stdev: {stdev} with: {param}") 
print(f"Best: {grid_result.best_score_} using {grid_result.best_params_}")

C:\Users\daani\AppData\Local\Programs\Python\Python37\lib\site-packages\sklearn\model_selection\_split.py:2053: FutureWarning: You should specify a value for 'cv' instead of relying on the default value. The default value will change from 3 to 5 in version 0.22.
  warnings.warn(CV_WARNING, FutureWarning)


Train on 161 samples
Epoch 1/20
161/161 [==============================] - 0s 2ms/sample - loss: 0.6581 - accuracy: 0.6149
Epoch 2/20
161/161 [==============================] - 0s 136us/sample - loss: 0.6063 - accuracy: 0.6708
Epoch 3/20
161/161 [==============================] - 0s 192us/sample - loss: 0.5671 - accuracy: 0.6957
Epoch 4/20
161/161 [==============================] - 0s 180us/sample - loss: 0.5347 - accuracy: 0.7391
Epoch 5/20
161/161 [==============================] - 0s 198us/sample - loss: 0.5077 - accuracy: 0.7453
Epoch 6/20
161/161 [==============================] - 0s 180us/sample - loss: 0.4838 - accuracy: 0.7516
Epoch 7/20
161/161 [==============================] - 0s 149us/sample - loss: 0.4645 - accuracy: 0.7764
Epoch 8/20
161/161 [==============================] - 0s 198us/sample - loss: 0.4464 - accuracy: 0.8075
Epoch 9/20
161/161 [==============================] - 0s 167us/sample - loss: 0.4305 - accuracy: 0.8261
Epoch 10/20
161/161 [========================

C:\Users\daani\AppData\Local\Programs\Python\Python37\lib\site-packages\sklearn\model_selection\_search.py:841: DeprecationWarning: The default of the `iid` parameter will change from True to False in version 0.22 and will be removed in 0.24. This will change numeric results when test-set sizes are unequal.
  DeprecationWarning)


Train on 242 samples
Epoch 1/20
242/242 [==============================] - 0s 1ms/sample - loss: 0.7510 - accuracy: 0.5702
Epoch 2/20
242/242 [==============================] - 0s 140us/sample - loss: 0.6798 - accuracy: 0.6364
Epoch 3/20
242/242 [==============================] - 0s 169us/sample - loss: 0.6225 - accuracy: 0.7066
Epoch 4/20
242/242 [==============================] - 0s 149us/sample - loss: 0.5791 - accuracy: 0.7355
Epoch 5/20
242/242 [==============================] - 0s 157us/sample - loss: 0.5403 - accuracy: 0.7562
Epoch 6/20
242/242 [==============================] - 0s 165us/sample - loss: 0.5108 - accuracy: 0.7934
Epoch 7/20
242/242 [==============================] - 0s 206us/sample - loss: 0.4828 - accuracy: 0.8182
Epoch 8/20
242/242 [==============================] - 0s 227us/sample - loss: 0.4615 - accuracy: 0.8430
Epoch 9/20
242/242 [==============================] - 0s 198us/sample - loss: 0.4438 - accuracy: 0.8471
Epoch 10/20
242/242 [========================

In [29]:
# TUNING THE EPOCHS
param_grid = {'batch_size': [20],
              'epochs': [20, 40, 80, 160]}
# Create Grid Search
grid = GridSearchCV(estimator=model, param_grid=param_grid, n_jobs=1)
grid_result = grid.fit(X_train, y_train, verbose=True)

# Report Results
means = grid_result.cv_results_['mean_test_score']
stds = grid_result.cv_results_['std_test_score']
params = grid_result.cv_results_['params']
for mean, stdev, param in zip(means, stds, params):
    print(f"Means: {mean}, Stdev: {stdev} with: {param}") 
print(f"Best: {grid_result.best_score_} using {grid_result.best_params_}")

Train on 161 samples
Epoch 1/20
161/161 [==============================] - 0s 2ms/sample - loss: 1.0279 - accuracy: 0.2733
Epoch 2/20
161/161 [==============================] - 0s 87us/sample - loss: 0.9772 - accuracy: 0.3106
Epoch 3/20
161/161 [==============================] - 0s 93us/sample - loss: 0.9314 - accuracy: 0.3230
Epoch 4/20
161/161 [==============================] - 0s 99us/sample - loss: 0.8930 - accuracy: 0.3416
Epoch 5/20
161/161 [==============================] - 0s 105us/sample - loss: 0.8571 - accuracy: 0.3665
Epoch 6/20
161/161 [==============================] - 0s 155us/sample - loss: 0.8198 - accuracy: 0.3975
Epoch 7/20
161/161 [==============================] - 0s 105us/sample - loss: 0.7879 - accuracy: 0.4161
Epoch 8/20
161/161 [==============================] - 0s 124us/sample - loss: 0.7602 - accuracy: 0.4348
Epoch 9/20
161/161 [==============================] - 0s 105us/sample - loss: 0.7348 - accuracy: 0.4720
Epoch 10/20
161/161 [===========================

C:\Users\daani\AppData\Local\Programs\Python\Python37\lib\site-packages\sklearn\model_selection\_search.py:841: DeprecationWarning: The default of the `iid` parameter will change from True to False in version 0.22 and will be removed in 0.24. This will change numeric results when test-set sizes are unequal.
  DeprecationWarning)


Train on 242 samples
Epoch 1/80
242/242 [==============================] - 0s 1ms/sample - loss: 1.1272 - accuracy: 0.2893
Epoch 2/80
242/242 [==============================] - 0s 74us/sample - loss: 1.0502 - accuracy: 0.3099
Epoch 3/80
242/242 [==============================] - 0s 74us/sample - loss: 0.9746 - accuracy: 0.3554
Epoch 4/80
242/242 [==============================] - 0s 78us/sample - loss: 0.9139 - accuracy: 0.3884
Epoch 5/80
242/242 [==============================] - 0s 74us/sample - loss: 0.8556 - accuracy: 0.4132
Epoch 6/80
242/242 [==============================] - 0s 70us/sample - loss: 0.8054 - accuracy: 0.4298
Epoch 7/80
242/242 [==============================] - 0s 74us/sample - loss: 0.7620 - accuracy: 0.5000
Epoch 8/80
242/242 [==============================] - 0s 74us/sample - loss: 0.7251 - accuracy: 0.5496
Epoch 9/80
242/242 [==============================] - 0s 95us/sample - loss: 0.6917 - accuracy: 0.5785
Epoch 10/80
242/242 [==============================] 

In [32]:
# hyperparameter tuning at least 3 parameters
def create_model(neurons, activation, optimizer):
    # create model
    model = Sequential()
    model.add(Dense(neurons, input_dim=13, activation=activation))
    model.add(Dense(1, activation='sigmoid'))
    # Compile model
    model.compile(loss='binary_crossentropy', optimizer=optimizer, metrics=['accuracy'])
    return model

# create model
model = KerasClassifier(build_fn=create_model, verbose=0)

In [33]:
param_grid = {"batch_size":[20],
              "epochs": [80],
              "neurons": [15, 25, 30],
              "activation": ['relu', 'sigmoid'],
              "optimizer": ['adam', 'SGD']
             }

# Create Grid Search
grid = GridSearchCV(estimator=model, param_grid=param_grid, n_jobs=1)
grid_result = grid.fit(X_train, y_train, verbose=True)

# Report Results
means = grid_result.cv_results_['mean_test_score']
stds = grid_result.cv_results_['std_test_score']
params = grid_result.cv_results_['params']
for mean, stdev, param in zip(means, stds, params):
    print(f"Means: {mean}, Stdev: {stdev} with: {param}") 
print(f"Best: {grid_result.best_score_} using {grid_result.best_params_}")

Train on 161 samples
Epoch 1/80
161/161 [==============================] - 0s 2ms/sample - loss: 0.8326 - accuracy: 0.4348
Epoch 2/80
161/161 [==============================] - 0s 105us/sample - loss: 0.7884 - accuracy: 0.4969
Epoch 3/80
161/161 [==============================] - 0s 87us/sample - loss: 0.7517 - accuracy: 0.5155
Epoch 4/80
161/161 [==============================] - 0s 93us/sample - loss: 0.7205 - accuracy: 0.5466
Epoch 5/80
161/161 [==============================] - 0s 136us/sample - loss: 0.6917 - accuracy: 0.5776
Epoch 6/80
161/161 [==============================] - 0s 93us/sample - loss: 0.6677 - accuracy: 0.5963
Epoch 7/80
161/161 [==============================] - 0s 81us/sample - loss: 0.6442 - accuracy: 0.6149
Epoch 8/80
161/161 [==============================] - 0s 74us/sample - loss: 0.6222 - accuracy: 0.6211
Epoch 9/80
161/161 [==============================] - 0s 62us/sample - loss: 0.6013 - accuracy: 0.6398
Epoch 10/80
161/161 [==============================

C:\Users\daani\AppData\Local\Programs\Python\Python37\lib\site-packages\sklearn\model_selection\_search.py:841: DeprecationWarning: The default of the `iid` parameter will change from True to False in version 0.22 and will be removed in 0.24. This will change numeric results when test-set sizes are unequal.
  DeprecationWarning)


Train on 242 samples
Epoch 1/80
242/242 [==============================] - 0s 1ms/sample - loss: 0.6713 - accuracy: 0.6281
Epoch 2/80
242/242 [==============================] - 0s 78us/sample - loss: 0.6444 - accuracy: 0.7149
Epoch 3/80
242/242 [==============================] - 0s 107us/sample - loss: 0.6207 - accuracy: 0.7479
Epoch 4/80
242/242 [==============================] - 0s 103us/sample - loss: 0.6008 - accuracy: 0.7686
Epoch 5/80
242/242 [==============================] - 0s 91us/sample - loss: 0.5821 - accuracy: 0.7686
Epoch 6/80
242/242 [==============================] - 0s 103us/sample - loss: 0.5643 - accuracy: 0.7810
Epoch 7/80
242/242 [==============================] - 0s 111us/sample - loss: 0.5483 - accuracy: 0.7893
Epoch 8/80
242/242 [==============================] - 0s 87us/sample - loss: 0.5329 - accuracy: 0.7975
Epoch 9/80
242/242 [==============================] - 0s 99us/sample - loss: 0.5187 - accuracy: 0.8017
Epoch 10/80
242/242 [============================